# Generated by Django 4.1.4 on 2023-05-15 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_rename_propertytypes_propertytype'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='availability_from',
            field=models.DateField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listing',
            name='availability_to',
            field=models.DateField(default=None),
            preserve_default=False,
        ),
    ]
