# Generated by Django 4.1.4 on 2023-05-15 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_listing_availability_from_listing_availability_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='availability_from',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='availability_to',
            field=models.DateField(blank=True),
        ),
    ]
