# Generated by Django 4.1.4 on 2023-05-15 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_alter_listing_availability_from_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='availability_from',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='listing',
            name='availability_to',
            field=models.DateField(),
        ),
    ]
