# Generated by Django 4.1.4 on 2023-05-16 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_alter_listing_availability_from_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='price_per_day',
            new_name='price_per_night',
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='name',
            new_name='title',
        ),
    ]
