# Generated by Django 4.1.4 on 2023-05-19 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0009_rename_price_per_day_listing_price_per_night_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='gps_location',
        ),
        migrations.AddField(
            model_name='listing',
            name='geolat',
            field=models.FloatField(default=50.0874654, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listing',
            name='geolng',
            field=models.FloatField(default=14.4212535, max_length=150),
            preserve_default=False,
        ),
    ]
