# Generated by Django 4.1.4 on 2023-05-21 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0011_alter_listing_description_alter_listing_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailableDates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='listing',
            name='available_dates',
            field=models.ManyToManyField(blank=True, related_name='availability', to='booking.availabledates'),
        ),
    ]
