# Generated by Django 4.1.4 on 2023-05-21 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0012_availabledates_listing_available_dates'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AvailableDates',
            new_name='AvailableDate',
        ),
    ]
